---
- name: Get Shodan Host Count
  hosts: localhost
  tasks:
    - name: Get Shodan Host Count
      simeononsecurity.ansible_shodan.get_shodan_host_count:
        api: "{{ shodan_api_key }}"
        query: "apache"
        facet: "org"
        minify: true
      register: shodan_host_count_result

    - name: Display Shodan Host Count
      debug:
        var: shodan_host_count_result.result
